// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByxfevwbb0ABEZjAhGIWX8jw5STHniIRs',
    appId: '1:520370567862:web:c0ef778a6f65b903ebc417',
    messagingSenderId: '520370567862',
    projectId: 'testpokemon-b1dbc',
    authDomain: 'testpokemon-b1dbc.firebaseapp.com',
    databaseURL: 'https://testpokemon-b1dbc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testpokemon-b1dbc.appspot.com',
    measurementId: 'G-CFC8SN26HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu6al3dBipUip0XyA0ZiixZj0DBG3L-jA',
    appId: '1:520370567862:android:23cf2f868f7cb0e0ebc417',
    messagingSenderId: '520370567862',
    projectId: 'testpokemon-b1dbc',
    databaseURL: 'https://testpokemon-b1dbc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testpokemon-b1dbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOSGurCKDhKZH-oW9MevJ-6S05sJIWttw',
    appId: '1:520370567862:ios:d8bc818750e75709ebc417',
    messagingSenderId: '520370567862',
    projectId: 'testpokemon-b1dbc',
    databaseURL: 'https://testpokemon-b1dbc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testpokemon-b1dbc.appspot.com',
    iosClientId: '520370567862-8nlkupbrdnq5717fpth8qat6bev9eks0.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
